// acount-react/shared/ui/progress.js
import React from 'react'

import { Percent } from './format'

import './progress.scss'
const BASE_CLASS = `progress`

export function Progress( props ) {
  const { max, value, tableLayout } = props
  const percent    = value / max
  const cssPercent = Math.max( 0, Math.min(100, percent * 100) )
  const width      = Number.isNaN( cssPercent ) ? `0` : `${ cssPercent }%`
  const COMP_CLASS = [ BASE_CLASS ]
  if ( tableLayout ) COMP_CLASS.push( `${BASE_CLASS}--table-layout` )
  return (
    <dl className={ COMP_CLASS.join(` `) } >
      <dt className={`${BASE_CLASS}__label`}>
        <Percent value={ percent } />
      </dt>
      <dd
        className={`${BASE_CLASS}__bar`}
        style={{width}}
      />
    </dl>
  )
}

// acount-nuxt/components/ui/progress.vue
<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: `acount-progress`,
  props: {
    value: {
      type: Number,
      required: true,
    },
    max: {
      type: Number,
      required: true,
    },
  },
  computed: {
    percent(): number {
      const percent = this.value / this.max
      const cssPercent = Math.max(0, Math.min(100, percent * 100))
      return isNaN(cssPercent) ? 0 : cssPercent
    },
  },
})
</script>

<template lang="pug">
dl.acount-progress
  dt.acount-progress__label
    | {{ $n(percent / 100, 'percent') }}
  dd.acount-progress__bar
    v-progress-linear(
      color="info"
      height="20"
      :value="percent"
    )
</template>

<style lang="scss" scoped>
.acount-progress {
  position: relative;
  margin: 0;
}
.acount-progress__label {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
.v-progress-linear {
  margin: 0;
}
</style>
